print("Hello Oury this is daddy  .. Hawlatou is coming ")
print("Hello World")
print("I have a dream that my 4 little children will one day live in a nation where they will not be juddge at all")
print("Hello Oury")
print("test1")
